dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
    dist: xenial
    sudo: true
  - python: "3.8-dev"
    dist: xenial
    sudo: true
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then if_pylint=:; fi
install:
- pip install pydiatra
- pip install $pyflakes
- $if_pylint pip install pylint
- $if_pygments pip install docutils pygments
- git clone https://github.com/progrhyme/shove.git ~/shove
- mkdir -p ~/.local/bin
- ln -sf ~/shove/bin/shove ~/.local/bin
- shove -V
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python -m pydiatra .
- python -m pyflakes .
- $if_pylint private/run-pylint
- $if_pygments private/check-rst
- make test
- python setup.py install
- cd /
- python -c 'import distutils644'

# vim:ts=2 sts=2 sw=2 et
