language: python
python:
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 2.6 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- pip install pydiatra
- pip install pyflakes
- pip install pylint
script:
- python -m pydiatra *.py
- python -m pyflakes *.py
- $no_pylint || private/run-pylint
- python setup.py sdist
- tar -tvvf dist/distutils644-*.tar.gz | { ! grep -v -E '^(drwxr-xr-x|-rw-r--r--|-rwxr-xr-x) root/root '; }
- zcat dist/distutils644-*.tar.gz | file - | grep -w 'POSIX tar archive'

# vim:ts=2 sts=2 sw=2 et
